entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker: {}

api:
  dashboard: true

certificatesResolvers:
  selfsigned:
    acme:
      email: "you@example.com"
      storage: "/etc/traefik/acme.json"
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web